import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    backgroundColor: "#1c2161",
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
    borderRadius: 10,
  },
  profileTitleText: {
    fontWeight: "bold",
    color: "#1c2161",
    fontSize: 30,
    marginBottom: 20,
    top: 0,
  },
  profileContainer: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
    borderRadius: 10,
  },
  tabNavigator: { marginBottom: -28 },
  mainContainer: {
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
    zIndex: 1,
  },
  createAccountContainer: {
    flex: 1,
    backgroundColor: "#1c2161",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 40,
  },
  invalidView: {
    position: "absolute",
    top: 10,
  },
  invalidText: { color: "white" },
  invertContainer: {
    flex: 1,
    // marginTop: 10,
    backgroundColor: "#1c2161",
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
  },
  containeruser: {
    flex: 1,
    marginTop: 10,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
    fontSize: 30,
  },
  containeruser1: {
    backgroundColor: "#fff",
    marginBottom: 20,
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
    fontSize: 30,
  },

  profileImage: {
    height: 250,
    width: 250,
  },

  mainTitle: {
    fontSize: 40,
  },
  qrcode: {
    marginBottom: 30,
    marginTop: 50,
    fontSize: 30,
  },
  qrcontainer: {
    flex: 1,
    marginTop: 10,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
    fontSize: 30,
  },
  tinyLogoContainer: {
    backgroundColor: "#1c2161",
  },
  tinyLogo: {
    marginTop: 50,
    width: 380,
    height: 200,
  },
  loadingScreen: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginRight: -25,
  },
  dotsWrapper: {
    width: 50,
  },
  qrcodebottom: {
    backgroundColor: "#151C47",
    width: 1200,
    marginTop: 100,
    height: 50,
  },
  qrcodebottom2: {
    backgroundColor: "#151C47",
    width: 1200,
    marginTop: 20,
    height: 20,
  },
  topBar: {
    marginTop: -200,
    backgroundColor: "#151C47",
    width: 1200,
    height: 370,
    alignItems: "center",
  },
  login: {
    flex: 1,
    marginTop: -25,
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
    fontSize: 30,
  },
  login2: {
    flex: 1,
    marginTop: 10,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
    fontSize: 30,
  },
  login3: {
    fontSize: 40,
    marginTop: 10,
  },
  input: {
    height: 40,
    width: 343,
    margin: 8,
    padding: 28,
    borderRadius: 100,
    backgroundColor: "#FFF",
    fontSize: 18,
    color: "black",
  },
  signinButton: {
    margin: 8,
    alignItems: "center",
    backgroundColor: "#fdef4c",
    padding: 20,
    borderRadius: 200,
    width: 343,
  },
  createAccountText: {
    color: "#fdef4c",
    alignItems: "center",
    justifyContent: "center",
  },
  signinButtonText: { fontSize: 18, color: "#151C47", fontWeight: "700" },
  titleText: {
    fontWeight: "bold",
    color: "#fff",
    fontSize: 30,
    marginTop: -20,
    marginBottom: 20,
  },
  homeTitleText: {
    fontWeight: "bold",
    color: "#1c2161",
    fontSize: 40,
    marginTop: 30,
    paddingBottom: 8,
    marginLeft: 38,
  },
  colorText: {
    color: "#151C47",
    fontWeight: "bold",
  },
  buttonQuill: {
    borderRadius: 10,
    borderWidth: 2,
    margin: 15,
    width: 330,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
  },
  lockImg: {
    height: 50,
    width: 50,
  },
  galleryImgMain: {
    width: 330,
    height: 240,
    borderRadius: 10,
    borderColor: "#151C47",
    borderWidth: 2,
  },
  galleryImg: {
    width: 330,
    height: 120,
    borderRadius: 10,
    borderColor: "#151C47",
    borderWidth: 2,
  },
  galleryText: { marginBottom: 15, fontSize: 19 },
  hcontainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    // padding: 10,
  },
  h2container: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
    borderRadius: 10,
  },
  h3container: {
    display: "flex",
    alignItems: "center",
    textAlign: "left",
    justifyContent: "center",
    borderRadius: 10,
    width: 340,
  },

  quill: { width: 50, height: 50 },
  modalContainer: {
    flex: 1,
    backgroundColor: "#151C47",
  },
  list: {
    backgroundColor: "white",
  },
  profileList: {
    backgroundColor: "white",
  },
  profileSwitchTitle: { fontSize: 20 },
  modalFlatlistContiner: {
    flex: 1,
    justifyContent: "center",
  },
  modalCellOutline: {
    borderWidth: 1,
    borderColor: "black",
    alignItems: "center",
    marginHorizontal: 20,
    paddingVertical: 15,
    borderRadius: 8,
  },
  modalTitle: {
    flex: 1,
    backgroundColor: "#151C47",
  },
  modalTitleText: {
    marginTop: 40,
    fontSize: 30,
    fontWeight: "bold",
    marginHorizontal: 20,
    textAlign: "center",
    color: "#FFF",
  },
  modalButton: {
    backgroundColor: "#FFF",
    justifyContent: "center",
    alignItems: "center",
    height: 50,
    marginHorizontal: 20,
    marginBottom: 5,
    borderRadius: 8,
  },
});
